name: Check Types

on: [push, pull_request]

jobs:
  check-types:
    name: check-types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun run check-types
